config/routes.rb
Rails.application.routes.draw do
  get 'csvs/new' 
  post 'csvs/csv_import'
  get 'csvs/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/csvs_controller.rb
require 'csv'

class CsvsController < ApplicationController
  def new
  end

  def csv_import
   csv_file_path = "tmp/uploaded_file.csv"
   File.write(csv_file_path, params[:fileupload].read)
   ImportCsvJob.perform_async(csv_file_path)
  end

  def show
  	# csv_data = CSV.open("tmp/uploaded_file.csv",:headers =>true).read
  	# byebug
    @data = User.paginate(:page => params[:page], :per_page => 30)

  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/csvs_helper.rb
module CsvsHelper
end

app/views/csvs/csv_import.html.erb
<h1>This is the csv page</h1>

app/views/csvs/new.html.erb
<%= form_tag csvs_csv_import_path, multipart: true do %>
	<%= file_field_tag :fileupload %> 
    <%= submit_tag :submit %>
<% end %>

app/views/csvs/show.html.erb
<h1>CONTENT OF FILE </h1>
<table>
 <tr>
 <th>NAME</th>
 <th>EMAIL</th>
 </tr>
<% @data.each do |r| %>
   <tr>
   	<td><%= r.name %></td>
   	<td><%= r.email %></td>
   </tr>
 <% end %>
   

</table>
<%= will_paginate @data %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backgroundjob</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>